[package]
name = "coap-server-tokio"
version = "0.1.2"
description = "Robust async CoAP server (tokio support)"
authors = ["Josh Guilfoyle <jasta@devtcg.org>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jasta/coap-server-rs"
categories = ["network-programming"]
keywords = ["coap", "server", "async", "IoT"]
edition = "2021"

[features]
default = ["net"]
net = ["tokio/net", "tokio-util"]

[dependencies]
coap-server = { path = "../coap-server" }
tokio = { version = "1.17.0", features = ["rt", "macros"] }
tokio-util = { version = "0.7.0", features = ["codec", "net"], optional = true }
bytes = { version = "1.1.0", default-features = false }
futures = { version = "0.3.21", default-features = false }
async-trait = "0.1.53"
pin-project = "1.0.10"
log = "0.4.16"
coap-lite = { version = "0.9.0", default-features = false }

[dev-dependencies]
async-stream = "0.3.3"
tokio = { version = "1.17.0", features = ["test-util", "rt-multi-thread"] }
env_logger = "0.9.0"
